### ISSUE TITLE
Fix the this.emit.error in the wuf unit test 

### ISSUE THREAD

**Issue by weichenchao1004** [anvil-open-software/wuf#33]

**Comment by luvaas** [comment]
This was a problem with the ngxMdModule.  If the spec file that used ngxMdModule did not ALSO include HttpClientTestingModule, this.emit.error messages would appear on pages completely unrelated to ngxMdModule and also prevent us from seeing other test errors throughout the app.  So the fix was to add HttpClientTestingModule to imports in .spec files wherever ngxMdModule was used and THEN fix any other broken tests that may have been failing silently as a result of the ngxMdModule issue.

**Comment by luvaas** [comment]
Fixed with merge of WUF-33
